// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phgtlaznfckcxtaqxecb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZ3RsYXpuZmNrY3h0YXF4ZWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTM4NzgsImV4cCI6MjA2MDYyOTg3OH0.eSZtnwy8AIVOf5cXgx0lb1yjCtlfbIJdGS4JCMIQZVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);